#!/usr/bin/env bash
#script that transfer file b/n client and server

if [ $# -lt 2 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP"
    exit;
fi

scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$1" ubuntu@"$2":~/
