#!/bin/bash
# this script automize git add commit and push 

if [ $# == 0 ]
then
	# addd everyy thing and push with commit msg hot_fix
	git add .
	git commit -m "hot_fix"
	git push
elif [ $# == 1 ]
then
	# add $1 and with commit msg hot_fix push
	git add "$1"
	git commit -m "hot_fix"
	git push
else
	# add $1 and with commit msg $2 push
	git add "$1"
	git commit -m "$2"
	git push
fi
