#!/bin/bash
# this script automize git add commit and push 

if [ $# == 0 ]
then
	# addd everyy thing and push with commit msg hot_fix
	ssh -i ~/.ssh/id_rsa ubuntu@34.232.69.130
elif [ $1 == 2 ]
then
	# add $1 and with commit msg hot_fix push
	ssh -i ~/.ssh/id_rsa ubuntu@100.26.216.95
elif [ $1 == 3 ]
then
	# add $1 and with commit msg $2 push
	ssh -i ~/.ssh/id_rsa ubuntu@100.24.205.204
else
	echo "Usage: (ser) main server (ser1) second server (ser2) third server"
fi
